#!/usr/bin/env python3
"""Generate deterministic, mechanically repetitive DNS lab fixtures."""

from __future__ import annotations

import argparse
import dataclasses
import json
import pathlib


@dataclasses.dataclass(frozen=True)
class Fixture:
    qtype: str
    records: tuple[str, ...]
    minimum_tcp_bytes: int
    maximum_tcp_bytes: int


def _txt_record(owner: str, chunks: int, chunk_size: int) -> str:
    strings = "\n".join(f'    "{"x" * chunk_size}"' for _ in range(chunks))
    return f"{owner} 60 IN TXT (\n{strings}\n)"


def build_fixtures() -> dict[str, Fixture]:
    return {
        "large-512": Fixture(
            qtype="TXT",
            records=(_txt_record("large-512", 4, 200),),
            minimum_tcp_bytes=700,
            maximum_tcp_bytes=1_200,
        ),
        "large-1232": Fixture(
            qtype="TXT",
            records=(_txt_record("large-1232", 8, 200),),
            minimum_tcp_bytes=1_500,
            maximum_tcp_bytes=2_200,
        ),
        "large-multi-a": Fixture(
            qtype="A",
            records=tuple(
                f"large-multi-a 60 IN A 192.0.2.{suffix}"
                for suffix in range(1, 129)
            ),
            minimum_tcp_bytes=2_000,
            maximum_tcp_bytes=4_000,
        ),
        "large-multi-aaaa": Fixture(
            qtype="AAAA",
            records=tuple(
                f"large-multi-aaaa 60 IN AAAA 2001:db8:1::{suffix:x}"
                for suffix in range(1, 129)
            ),
            minimum_tcp_bytes=3_000,
            maximum_tcp_bytes=6_000,
        ),
        "large-srv": Fixture(
            qtype="SRV",
            records=tuple(
                f"large-srv 60 IN SRV {priority} 100 389 srv-{priority + 1}.example.test."
                for priority in range(64)
            ),
            minimum_tcp_bytes=2_000,
            maximum_tcp_bytes=8_000,
        ),
        "near-max-tcp": Fixture(
            qtype="TXT",
            records=(_txt_record("near-max-tcp", 240, 250),),
            minimum_tcp_bytes=58_001,
            maximum_tcp_bytes=65_535,
        ),
    }


def render_zone(fixtures: dict[str, Fixture]) -> str:
    lines = [
        "; Generated by generate-large-fixtures.py. Do not edit.",
        "$ORIGIN example.test.",
    ]
    for name in sorted(fixtures):
        lines.extend(fixtures[name].records)
    return "\n".join(lines) + "\n"


def build_manifest(fixtures: dict[str, Fixture]) -> dict[str, object]:
    entries = {}
    for name, fixture in sorted(fixtures.items()):
        entries[name] = {
            "answer_count": len(fixture.records),
            "maximum_tcp_bytes": fixture.maximum_tcp_bytes,
            "minimum_tcp_bytes": fixture.minimum_tcp_bytes,
            "qname": f"{name}.example.test",
            "qtype": fixture.qtype,
        }
    return {"schema_version": 1, "fixtures": entries}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zone-output", required=True, type=pathlib.Path)
    parser.add_argument("--manifest-output", required=True, type=pathlib.Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    zone_output = args.zone_output.resolve()
    manifest_output = args.manifest_output.resolve()
    if zone_output == manifest_output:
        raise SystemExit("zone and manifest output paths must be different")

    zone_output.parent.mkdir(parents=True, exist_ok=True)
    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    fixtures = build_fixtures()
    zone_output.write_text(render_zone(fixtures), encoding="utf-8", newline="\n")
    manifest_output.write_text(
        json.dumps(build_manifest(fixtures), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
