options {
    directory "/var/cache/bind";
    listen-on port 5353 { any; };
    listen-on-v6 port 5353 { any; };
    recursion no;
    dnssec-validation no;
    allow-query { any; };
    allow-transfer { none; };
    allow-update { none; };
    notify no;
    pid-file "/var/cache/bind/named.pid";
    session-keyfile "/var/cache/bind/session.key";
};
zone "dns.quality-assurance.fyi" {
    type primary;
    file "/var/cache/bind/db.dns.quality-assurance.fyi";
    inline-signing yes;
    dnssec-policy default;
    key-directory "/var/cache/bind/keys";
};
